import type { Metadata } from "next";
import { Kiwi_Maru } from "next/font/google";
import "./globals.css";

const kiwiMaru = Kiwi_Maru({
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${kiwiMaru.className}`}>
                <header style={{ background: "var(--color-1)" }}>
                    <div className="header-container">
                        <h1 className="header-title">My Portfolio</h1>
                    </div>
                </header>
                <main className="main">{children}</main>
                <footer style={{ display: "flex", justifyContent: "center" }}>
                    <div className="container">
                        <p style={{ textAlign: "center" }}>
                            &copy; {new Date().getFullYear()} My Portfolio
                        </p>
                    </div>
                </footer>
            </body>
        </html>
    );
}
